config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  resources :tasks
  resources :tags

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :tasks
  validates :name, :presence => true, :uniqueness => true
end

app/models/task.rb
class Task < ActiveRecord::Base
  has_and_belongs_to_many :tags
  validates :content, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.order(:name)
  end
  
  def show
    begin
      @tag = Tag.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to tags_path
      return
    end
    @tasks = @tag.tasks
    @title = "Tag: #{@tag.name}"
    render "tasks/index"
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    redirect_to :back
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
    @title = "To-Do List"
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.new(params.require(:task).permit(:content))
    if @task.save
      #Save relevant Tags
      if params[:tag_names] != ''
        tag_names = params[:tag_names].split(',')
	tag_names.reject!(&:empty?)
        tag_names.each do |tag_name|
          tag_name.chomp!
          @tag = Tag.find_or_create_by(name: tag_name)
          @task.tags << @tag 
        end
      end
      redirect_to tasks_path
    else
      render 'new'
    end
  end

  def update
    @task = Task.find(params[:id])
    
    if @task.update(params.require(:task).permit(:content,:done))
      redirect_to tasks_path
    else
      render 'edit'
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @tags = @task.tags.clone
    @tags.each do |tag|
      tag.tasks.destroy(@task)
      puts "Tag name: #{tag.name}, Empty?: #{tag.tasks(true).empty?}"
      if tag.tasks(true).empty?
        tag.destroy
      end
    end

    @task.destroy

    redirect_to :back
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js" %>
    <%= javascript_include_tag "bootstrap.min" %>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <%= javascript_include_tag "IE/ie10-viewport-bug-workaround" %>

app/views/layouts/_header.html.erb
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <%= favicon_link_tag 'list_dl.ico' %>

    <title>To-do Manager</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <!-- Bootstrap core CSS -->
    <%= stylesheet_link_tag "bootstrap-min" %>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <%= stylesheet_link_tag "IE/ie10-viewport-bug-workaround" %>

    <!-- Custom styles for this template -->
    <%= stylesheet_link_tag "starter-template" %>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

app/views/layouts/_navbar.html.erb
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'CVWO Assignment 3', root_path, class:"navbar-brand" %>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li <% if current_page?(root_path) %> class="active" <% end %> ><%= link_to 'Home', root_path %></li>
            <li <% if current_page?(controller:"tasks", action:"index") %> class="active" <% end %> ><%= link_to 'To do List', tasks_path %></li>
            <li <% if current_page?(controller:"tasks", action:"new") %> class="active" <% end %> ><%= link_to 'New Task', new_task_path %></li>
	    <li <% if current_page?(controller:"tags") %> class="active" <% end %> ><%= link_to 'Tags', tags_path %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<%= render "layouts/header" %>

  <body>
    <%= render "layouts/navbar" %>
    <div class="container">
	<%= yield %>
    </div><!-- /.container -->

    <%= render "layouts/footer" %>
  </body>
</html>

app/views/tags/index.html.erb
<div class="starter-template">
  <div class="panel panel-default">
    <div class="panel-heading"><h1>Tags (Alphabetical) <%= image_tag "tag.png" %></h1></div>
    <ul class="list-group">
      <% @tags.each do |tag| %>
      <li class="list-group-item"><%= link_to tag.name, tag_path(tag), class: 'btn btn-default' %>
                                  <%= link_to 'Delete Tag', tag_path(tag), method: :delete, data: {confirm: 'Are you sure?'}%></li>
      <% end %>
    </ul>
    </div>
  </div>
</div>

app/views/tasks/edit.html.erb
<div class="form-header">
  <h2 class="form-title">Edit Task</h2>
</div>

  <% if @task.errors.any? %>
    <div class="panel panel-danger">
      <div class="panel-body">
	<%= pluralize(@task.errors.count, "error") %>
	prohibited this task from being saved:
      </div>
      <div class="panel-footer">    
      <ul>
	<% @task.errors.full_messages.each do |msg| %>
	  <li><%= msg %></li>
	<% end %>
      </ul>
      </div>
    </div>
  <% end %>

<%= form_for @task, html: {class:'form_group', role:'form'} do |f| %>
  <div class="form-group">
    <%= f.label :content, 'Task' %><br>
    <%= f.text_field :content, class:'form-control', required:true, autofocus:true  %>
  </div>
  <div>
    <%= f.check_box :done %>
    <%= f.label :done, 'Done?' %>
  </div><br>
  <div class="form-group">
    <%= f.submit 'Update Task', class:'btn btn-default' %>
  </div>
<% end %>

app/views/tasks/index.html.erb
<div class="starter-template">
  <div class="panel panel-default">
    <div class="panel-heading"><h1><%= @title %> <%= image_tag 'todo-list.png' %></h1></div>
    <table class="table">
      <tr>
        <th>Task</th>
        <th>Edit</th>
        <th>Delete</th>
        <th>Tags</th>
      </tr>
      <% @tasks.each do |task| %>
      <tr>
        <td <% if task.done == true %>class='done'<% end %>><%= task.content %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Delete', task_path(task), method: :delete, data: {confirm: 'Are you sure?'} %></td>
        <td><% task.tags.each do |tag| %>
          <%= link_to tag.name, tag_path(tag), class: 'btn btn-default' =%>
        <% end %></td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="form-header">
  <h2 class="form-title">New Task</h2>
</div>

  <% if @task.errors.any? %>
    <div class="panel panel-danger">
      <div class="panel-body">
	<%= pluralize(@task.errors.count, "error") %>
	prohibited this task from being saved:
      </div>
      <div class="panel-footer">    
      <ul>
	<% @task.errors.full_messages.each do |msg| %>
	  <li><%= msg %></li>
	<% end %>
      </ul>
      </div>
    </div>
  <% end %>

<%= form_for @task, url: {action: "create"}, html: {class:'form_group', role:'form'} do |f| %>
  <div class="form-group">
    <%= f.label :content, 'Task' %><br>
    <%= f.text_field :content, class:'form-control', required:true, autofocus:true  %>
  </div>
  <div class="form-group">
    <%= label_tag(:tag_names, "Tags to apply") %><br>
    <%= text_field_tag(:tag_names, nil, class: "form-control")  %>
    <p>separate with a comma</p>
  </div>
  <div class="form-group">
    <%= f.submit 'Add Task', class:'btn btn-default' %>
  </div>
<% end %>

app/views/welcome/index.html.erb
<div class="starter-template">
  <h1>To Do Manager (CVWO Assignment 3)</h1>
  <p>On the navigation bar there are 3 links. The first takes you to the list of tasks in your to-do-list, the second allows you to create new tasks, and the third allows you to see all the available tags (in alphabetical order) and select one of them which will then show only the tasks which has the tag.</p><br>

  <h3>First Link: To-do List</h3>
  <p>View All the Tasks, their tags, and the option to edit or delete them</p>

  <h3>Second Link: New Task</h3>
  <p>Allows you to create a new task, and assign it tags</p>

  <h3>Third Link: Tags</h3>
  <p>Able to view all available tags in alphabetical order</p>
  <p>May select specific tag to see all the tasks that has the tag</p>
</div>